-- Create wallets table for managing multiple wallets per user
CREATE TABLE wallets (
  -- Unique identifier for the wallet (auto-generated UUID)
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to users table
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Stellar wallet address (public key)
  address TEXT NOT NULL UNIQUE,

  -- Encrypted private key (only for invisible wallets)
  encrypted_private_key TEXT,

  -- Type of wallet: 'invisible' (generated by platform) or 'external' (user-owned)
  type TEXT NOT NULL CHECK (type IN ('invisible', 'external')),

  -- Timestamp when the wallet was created
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create index on user_id for faster lookups
CREATE INDEX idx_wallets_user_id ON wallets(user_id);

-- Create index on address for faster lookups
CREATE INDEX idx_wallets_address ON wallets(address);

-- Add comment to table
COMMENT ON TABLE wallets IS 'Stores wallet information including invisible (platform-generated) and external (user-connected) wallets';
COMMENT ON COLUMN wallets.encrypted_private_key IS 'AES-256-GCM encrypted private key, only populated for invisible wallets';
COMMENT ON COLUMN wallets.type IS 'invisible: generated by platform, external: user-connected wallet';

