-- ============================================
-- Migration 006: Wallets Table
-- ============================================
-- Creates the table to manage multiple wallets per user
-- Supports invisible wallets (generated by platform)
-- and external wallets (connected by user)
-- ============================================

CREATE TABLE wallets (
  -- Unique identifier (UUID)
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Reference to user
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Stellar wallet public address
  address TEXT NOT NULL UNIQUE,

  -- Wallet type: 'invisible' (platform-generated) or 'external' (user-owned)
  type TEXT NOT NULL CHECK (type IN ('invisible', 'external')),

  -- Encrypted private key (only for invisible wallets)
  encrypted_private_key TEXT,

  -- Creation timestamp
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes to optimize searches
CREATE INDEX idx_wallets_user_id ON wallets(user_id);
CREATE INDEX idx_wallets_address ON wallets(address);
CREATE INDEX idx_wallets_user_type ON wallets(user_id, type);

-- Constraint to ensure invisible wallets have encrypted private key
ALTER TABLE wallets ADD CONSTRAINT check_invisible_wallet_key
  CHECK (
    (type = 'invisible' AND encrypted_private_key IS NOT NULL) OR
    (type = 'external' AND encrypted_private_key IS NULL)
  );

-- Comments for documentation
COMMENT ON TABLE wallets IS 'Stores wallet information including invisible (platform-generated) and external (user-connected) wallets';
COMMENT ON COLUMN wallets.address IS 'Stellar wallet public address';
COMMENT ON COLUMN wallets.type IS 'Wallet type: invisible (platform-generated) or external (user-connected)';
COMMENT ON COLUMN wallets.encrypted_private_key IS 'AES-256-GCM encrypted private key, only for invisible wallets';
