import { Keypair } from "@stellar/stellar-sdk";
import {
  getStellarContractConfig,
  validateStellarContractConfig,
  type StellarContractConfig,
} from "@/config/stellar-contracts";
import { InternalServerError } from "@/utils/AppError";

/**
 * Stellar Client Factory
 * 
 * Centralized factory for creating and managing Stellar contract clients.
 * Provides singleton instances of contract clients with automatic configuration
 * and transaction signing.
 * 
 * Usage:
 *   const factory = StellarClientFactory.getInstance();
 *   const escrowClient = await factory.getEscrowFactory();
 *   const result = await escrowClient.deployNewEscrow(params);
 */
export class StellarClientFactory {
  private static instance: StellarClientFactory | null = null;
  
  private config: StellarContractConfig;
  private signerKeypair: Keypair;
  
  // Lazy-loaded client instances
  private escrowFactoryClient: any = null;
  private feeManagerClient: any = null;
  private userRegistryClient: any = null;
  
  /**
   * Private constructor - use getInstance() instead
   */
  private constructor() {
    // Load and validate configuration
    this.config = getStellarContractConfig();
    const validation = validateStellarContractConfig(this.config);
    
    if (!validation.valid) {
      throw new InternalServerError(
        "Invalid Stellar contract configuration",
        { errors: validation.errors }
      );
    }
    
    // Initialize signer keypair
    try {
      this.signerKeypair = Keypair.fromSecret(this.config.signerSecretKey);
    } catch (error) {
      throw new InternalServerError(
        "Failed to initialize Stellar signer keypair",
        { originalError: error instanceof Error ? error.message : String(error) }
      );
    }
  }
  
  /**
   * Get singleton instance of the factory
   */
  public static getInstance(): StellarClientFactory {
    if (!StellarClientFactory.instance) {
      StellarClientFactory.instance = new StellarClientFactory();
    }
    return StellarClientFactory.instance;
  }
  
  /**
   * Reset the singleton instance (useful for testing)
   */
  public static resetInstance(): void {
    StellarClientFactory.instance = null;
  }
  
  /**
   * Get the signer's public key
   */
  public getSignerPublicKey(): string {
    return this.signerKeypair.publicKey();
  }
  
  /**
   * Get the current network configuration
   */
  public getNetworkConfig(): {
    network: string;
    networkPassphrase: string;
    rpcUrl: string;
  } {
    return {
      network: this.config.network,
      networkPassphrase: this.config.networkPassphrase,
      rpcUrl: this.config.rpcUrl,
    };
  }
  
  /**
   * Get Escrow Factory contract client
   * 
   * The client will be lazily initialized on first call and cached for subsequent calls.
   * 
   * @returns Promise<any> - Typed client for escrow-factory contract
   * @throws InternalServerError if client initialization fails
   */
  public async getEscrowFactory(): Promise<any> {
    if (this.escrowFactoryClient) {
      return this.escrowFactoryClient;
    }
    
    try {
      // Dynamically import the generated client
      // This will be available after running the bindings generation script
      // @ts-ignore - Module will be generated by bindings script
      const { Client } = await import("@offerhub/escrow-factory-client");
      
      this.escrowFactoryClient = new Client({
        contractId: this.config.contracts.escrowFactory,
        networkPassphrase: this.config.networkPassphrase,
        rpcUrl: this.config.rpcUrl,
        publicKey: this.signerKeypair.publicKey(),
        signTransaction: async (tx: any) => {
          tx.sign(this.signerKeypair);
          return tx;
        },
      });
      
      return this.escrowFactoryClient;
    } catch (error) {
      throw new InternalServerError(
        "Failed to initialize Escrow Factory client",
        {
          originalError: error instanceof Error ? error.message : String(error),
          hint: "Ensure bindings have been generated by running: pnpm run bindings:generate",
        }
      );
    }
  }
  
  /**
   * Get Fee Manager contract client
   * 
   * The client will be lazily initialized on first call and cached for subsequent calls.
   * 
   * @returns Promise<any> - Typed client for fee-manager contract
   * @throws InternalServerError if client initialization fails
   */
  public async getFeeManager(): Promise<any> {
    if (this.feeManagerClient) {
      return this.feeManagerClient;
    }
    
    try {
      // Dynamically import the generated client
      // @ts-ignore - Module will be generated by bindings script
      const { Client } = await import("@offerhub/fee-manager-client");
      
      this.feeManagerClient = new Client({
        contractId: this.config.contracts.feeManager,
        networkPassphrase: this.config.networkPassphrase,
        rpcUrl: this.config.rpcUrl,
        publicKey: this.signerKeypair.publicKey(),
        signTransaction: async (tx: any) => {
          tx.sign(this.signerKeypair);
          return tx;
        },
      });
      
      return this.feeManagerClient;
    } catch (error) {
      throw new InternalServerError(
        "Failed to initialize Fee Manager client",
        {
          originalError: error instanceof Error ? error.message : String(error),
          hint: "Ensure bindings have been generated by running: pnpm run bindings:generate",
        }
      );
    }
  }
  
  /**
   * Get User Registry contract client
   * 
   * The client will be lazily initialized on first call and cached for subsequent calls.
   * 
   * @returns Promise<any> - Typed client for user-registry contract
   * @throws InternalServerError if client initialization fails
   */
  public async getUserRegistry(): Promise<any> {
    if (this.userRegistryClient) {
      return this.userRegistryClient;
    }
    
    try {
      // Dynamically import the generated client
      // @ts-ignore - Module will be generated by bindings script
      const { Client } = await import("@offerhub/user-registry-client");
      
      this.userRegistryClient = new Client({
        contractId: this.config.contracts.userRegistry,
        networkPassphrase: this.config.networkPassphrase,
        rpcUrl: this.config.rpcUrl,
        publicKey: this.signerKeypair.publicKey(),
        signTransaction: async (tx: any) => {
          tx.sign(this.signerKeypair);
          return tx;
        },
      });
      
      return this.userRegistryClient;
    } catch (error) {
      throw new InternalServerError(
        "Failed to initialize User Registry client",
        {
          originalError: error instanceof Error ? error.message : String(error),
          hint: "Ensure bindings have been generated by running: pnpm run bindings:generate",
        }
      );
    }
  }
  
  /**
   * Create a transaction signing function for custom clients
   * 
   * Use this if you need to create a custom client outside the factory
   * 
   * @returns Async function that signs transactions with the backend keypair
   */
  public getTransactionSigner(): (tx: any) => Promise<any> {
    return async (tx: any) => {
      tx.sign(this.signerKeypair);
      return tx;
    };
  }
}

// Export singleton instance getter for convenience
export const getStellarClientFactory = () => StellarClientFactory.getInstance();
